### ISSUE TITLE
Learning Phyloseq

### ISSUE THREAD

**Issue by J-Cos** [J-Cos/VerdeIslandPassage_Project#2]
Hi @om4017,  

This is an "issue". Normally these are used to note some piece of work that is required on the code. Perhaps a bug (something not working), a feature (adding something new) or a request for input from another member of the team if you're stuck with something.

In this case I'm using this to suggest your next coding task - please don't start this till next week though! Background reading is a good focus for this week. And it would probably be easiest for me to talk you through a couple more details on github before you start too.

**Next week**, it would be great for you to start learning how the phyloseq R package works. This is a very helpful package for metabarcoding analyses of all kinds. We'll be using it as the main workhorse for everything we do. I'm a big believer in learning by doing - it is how I learnt. So a good place to start would be following along with the tutorial at this link http://joey711.github.io/phyloseq-demo/Restroom-Biogeography.html (the links to download the data are included in the tutorial).

As you follow along with the tutorial write each of the instructions into an R script, and feel free to include comments wherever you are unsure about something. When you are done make your own pull request for me to review and accept the code. I can then answer any questions you have.

_This will be a very useful exercise as not only will it teach you the basics of phyloseq, but going forward you will also be able to modify the script produced for your first analyses on the Verde Island Passage data._

**Comment by om4017** [comment]
Hi Jake
So I got it to work (I had to do some thing in my mac console, the install the vctrs package then it finally worked. Anyway I went to retrieve the data from the colorado FTP page but it wasn't working. So I found on some forum apparently this server is permanently down? I will leave a link to the forum below. Anyway they also put in the forum there was a new location but in R it stated it was a 550 requested action? From all the googling does that mean I've been denied acces?

https://github.com/joey711/phyloseq/issues/491

**Comment by om4017** [comment]
Also I'm not sure if this has an impact but the versions of my packages for phyloseq and ggplot2 were different to the ones in the tutorial sheet. Will this make a difference?

**Comment by J-Cos** [comment]
Hi Olivia, 

Really good job trouble shooting this. It does look like the links to the data have gone dead. That is a shame! Sorry! Oh well don't worry I have a back up. I have just checked and the data is currently accessible for these tutorials so we should have no furhter issue on that front.

So please instead have a go at completing the phyloseq ordination and alpha diversity tutorials. These are:
https://joey711.github.io/phyloseq/plot_ordination-examples.html
https://joey711.github.io/phyloseq/plot_richness-examples.html

As before they include code and instructions, as you work through copy the code into your own script that can be run beginning to end and produce all the outputs. Just add any questions or thoughts you have as comments in the code as you go!

**Comment by om4017** [comment]
Hi Jake
Sorry to bother you. 
I think I've gotten a little bit confused about how to make the new branches. It's telling me I need to resolve my current index before switching branches? I'm not really sure what's going on to be honest.

I have sort of made comments explaining to myself certain things within the code that I've been Googling as I've been going along. However I have a some questions I've written on a separate piece of paper.  I was thinking maybe if I could try and create the branches now then we could maybe go through any questions I have in the next meeting and I can add the answers to my code? It will also give me a chance to see if I can figure out the answers on my own.

**Comment by J-Cos** [comment]
Have you got 15 mins to chat at 12:30?
________________________________

**Comment by J-Cos** [comment]
You've done a great job on this so I'm closing this issue now. Though make sure to resolve the changes I requested on the pull request.
