### ISSUE TITLE
Installing DESeq2

### ISSUE THREAD

**Issue by om4017** [J-Cos/VerdeIslandPassage_Project#6]
Hi @J-Cos 
I'm trying to install DESeq2 but I'm having some issues (I think I shared the code but I may also be having issues with that.) I think it's installed but when I use library or package_version it says that it can't be found. It also says in a warning message it won't be installed if it's got a current or newer version already installed? I'm a little confused

**Comment by J-Cos** [comment]
Hey @om4017 ,

I can't see any code, but maybe don't worry about deseq too much just yet, as you don't have taxonomic assignments to play with!

How are you getting on with the diversity analyses and thinking about how to plot and model these things (richness, composition etc.)?

Cheers,

**Comment by om4017** [comment]
Hey @J-Cos 
It's mostly been reading and familiarising myself with my old stats noted to be honest. I definitely more since our meeting yesterday but I'm going to see how I got on over the weekend.
