### ISSUE TITLE
Merging MPA data with phyloseq object and using github

### ISSUE THREAD

**Issue by om4017** [J-Cos/VerdeIslandPassage_Project#7]
Hi @J-Cos 
I've created a data frame to do with the MPA data (I basically assigned 0,1 or 2 for how protected the site is.) However I was using the merge_phyloseq function to add this to the phyloseq object and it's just come up with an extra column but with a bunch of NA's.

I would try to share this code with you but I think I'm still little confused about github. I'm a bit confused about this yellow square with the dot but from googling it's saying it's only partially executed or something.

Any guidance would be appreciated. Thanks, Liv.

**Comment by J-Cos** [comment]
We discussed in person.
